In [3]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [36]:
def scrape_coches_ocasion(url):

    respuesta_coches = requests.get(url)
    

    sopa_coches = BeautifulSoup(respuesta_coches.content,'html.parser')

    lista_nombre_coches = sopa_coches.find_all("h2", {"style": "overflow-x:hidden"})
    lista_precio_rebajado = sopa_coches.find_all("span", {"class": "jsx-2870186023 priceLast"})
    lista_precio_original = sopa_coches.find_all("span", {"class": "jsx-2689423372 price"})
    lista_info= sopa_coches.find_all("div", {"class": "jsx-2480038221 op-grid-card-info"})
    lista_km= []

    for coche in lista_info:
        busqueda= coche.find_all('span',{'class':'jsx-3960002075 detail big'})
        lista_km.append(busqueda[1].text)

    nombre_coches = [coche.getText() for coche in lista_nombre_coches]
    precio_original = [precio.getText() for precio in lista_precio_original]
    precio_rebajado = [precio.getText() for precio in lista_precio_rebajado ]

    encabezados = ["Coche", "Precio Original", "Precio Rebajado", "Kilometros"]

    df_coches = pd.DataFrame([nombre_coches,precio_original,precio_rebajado,lista_km]).T
    df_coches.columns = encabezados
    

    return df_coches

In [40]:
ocasion_plus = scrape_coches_ocasion("https://www.ocasionplus.com/ofertas-especiales")

In [39]:
ocasion_plus

,Coche,Precio Original,Precio Rebajado,Kilometros
0,Dacia Jogger S.L. Extreme TCe (110CV) 7 plazas,18.090€,19.990€,54.057 km
1,Nissan X-Trail dCi Tekna 4x2 XTronic (130CV),16.950€,18.500€,135.885 km
2,Opel Meriva 1.4 Selective (120CV),9.000€,10.900€,73.411 km
3,Renault Kangoo Furgon Z.E. (60 CV) AUTO,10.727€,12.200€,42.321 km
4,Citroen Grand C4 Picasso BlueHDI 150 Airdream ...,13.545€,17.750€,116.684 km
5,BMW Serie 3 320i AUTO (184 CV),17.450€,19.500€,129.655 km
6,Skoda Fabia 1.0 TSI (110cv) Ambition Plus,13.172€,14.990€,52.382 km
7,Audi A3 Sportback Sportback Attracted 1.6 TDI ...,13.954€,15.700€,146.731 km
8,Opel Corsa 1.5D DT Edition (102 CV),12.363€,13.650€,32.709 km
9,Audi A1 Sportback Sportback Attraction 1.6 TDI...,14.955€,16.700€,82.888 km
10,Mercedes-Benz Clase C C Coupe 43 Mercedes 4Mat...,44.454€,51.500€,91.525 km
11,Citroen C4 BlueHDi 110 S&S Feel (110 CV),15.809€,17.600€,37.882 km
12,Peugeot Traveller BlueHDi 120 S&S Business Lon...,28.400€,31.250€,77.831 km
13,Peugeot Traveller BlueHDi 120 S&S Business Lon...,28.445€,31.300€,72.170 km
14,BMW X1 sDrive18d (150 CV),18.150€,18.500€,117.610 km
15,Peugeot Traveller BlueHDi 120 S&S Business Lon...,28.354€,31.200€,78.792 km
16,Peugeot Traveller BlueHDi 120 S&S Business Lon...,28.354€,31.200€,70.193 km
17,Peugeot Traveller Business Long (120 CV) 9 Plazas,28.454€,31.400€,68.926 km
18,Peugeot Traveller Business Long (120 CV) 9 Plazas,28.445€,31.300€,74.763 km
19,Tesla Model 3 Gran Autonomía 4WD (498 CV) Auto,36.272€,39.990€,67.380 km